#!/usr/bin/env python3
"""Export model.json (from train_bnn.py) into weights.vh for the FPGA design.

The BNN engine consumes:
  - W1[i] : 4-bit pattern, one per hidden neuron i in 0..15
  - T1[i] : 3-bit threshold per hidden neuron
  - W2_c  : 16-bit pattern per output class c in 0..2

Bit ordering note: input_vec[0] holds feature 0 (sepal length, after binarize),
so W1[i][0] must match. We assemble each W1 row LSB-first to match.
"""

import json
import pathlib
import sys

ROOT     = pathlib.Path(__file__).parent
MODEL    = ROOT / "model.json"
OUT_VH   = ROOT.parent / "fpga" / "rtl" / "weights.vh"


def to_bits(values, width):
    """Pack a list of {0,1} (LSB-first) into a Verilog literal."""
    assert len(values) == width
    bits = "".join(str(int(v)) for v in reversed(values))
    return f"{width}'b{bits}"


def main():
    if not MODEL.exists():
        sys.exit(f"error: {MODEL} not found — run train_bnn.py first")

    m = json.loads(MODEL.read_text())
    W1 = m["W1"]                       # (4, 16) — feature x neuron
    T1 = m["T1"]                       # (16,)
    W2 = m["W2"]                       # (16, 3) — hidden x class
    classes = m["class_names"]

    # Transpose so W1_per_neuron[i] is the 4-bit weight vector for neuron i.
    W1_per_neuron = list(zip(*W1))     # 16 entries, each length 4
    W2_per_class  = list(zip(*W2))     # 3 entries, each length 16

    lines = [
        "// Auto-generated by training/export_weights.py — DO NOT EDIT BY HAND.",
        f"// Class names: {', '.join(classes)}",
        "",
        "// Layer 1 weights: W1[neuron] = 4-bit pattern.",
        "wire [3:0] W1 [0:15];",
    ]
    for i, w in enumerate(W1_per_neuron):
        lines.append(f"assign W1[{i:>2}] = {to_bits(w, 4)};")

    lines += ["", "// Layer 1 thresholds.", "wire [2:0] T1 [0:15];"]
    for i, t in enumerate(T1):
        lines.append(f"assign T1[{i:>2}] = 3'd{int(t)};")

    lines += ["", "// Layer 2 weights: one 16-bit pattern per class."]
    for c, w in enumerate(W2_per_class):
        lines.append(f"wire [15:0] W2_{c} = {to_bits(w, 16)};")

    OUT_VH.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_VH}")


if __name__ == "__main__":
    main()
