// Auto-generated by training/export_weights.py — DO NOT EDIT BY HAND.
// Class names: setosa, versicolor, virginica

// Layer 1 weights: W1[neuron] = 4-bit pattern.
wire [3:0] W1 [0:15];
assign W1[ 0] = 4'b0001;
assign W1[ 1] = 4'b0010;
assign W1[ 2] = 4'b0010;
assign W1[ 3] = 4'b1110;
assign W1[ 4] = 4'b0011;
assign W1[ 5] = 4'b0001;
assign W1[ 6] = 4'b0110;
assign W1[ 7] = 4'b1101;
assign W1[ 8] = 4'b1101;
assign W1[ 9] = 4'b1111;
assign W1[10] = 4'b1101;
assign W1[11] = 4'b0001;
assign W1[12] = 4'b1111;
assign W1[13] = 4'b0111;
assign W1[14] = 4'b0010;
assign W1[15] = 4'b0010;

// Layer 1 thresholds.
wire [2:0] T1 [0:15];
assign T1[ 0] = 3'd2;
assign T1[ 1] = 3'd3;
assign T1[ 2] = 3'd3;
assign T1[ 3] = 3'd3;
assign T1[ 4] = 3'd0;
assign T1[ 5] = 3'd3;
assign T1[ 6] = 3'd3;
assign T1[ 7] = 3'd3;
assign T1[ 8] = 3'd1;
assign T1[ 9] = 3'd2;
assign T1[10] = 3'd1;
assign T1[11] = 3'd2;
assign T1[12] = 3'd2;
assign T1[13] = 3'd2;
assign T1[14] = 3'd1;
assign T1[15] = 3'd3;

// Layer 2 weights: one 16-bit pattern per class.
wire [15:0] W2_0 = 16'b1101101001101110;
wire [15:0] W2_1 = 16'b0111010101110001;
wire [15:0] W2_2 = 16'b0011010110001000;
