#!/usr/bin/env python3
"""Convert an iCE40 bitstream (.bin) into a C header for embedding in firmware."""

import argparse
import pathlib
import sys
import textwrap

HEADER = """\
#pragma once
// Auto-generated by firmware/scripts/bin2c.py from {src}.
// {nbytes} bytes.

#include <stddef.h>
#include <stdint.h>

static const uint8_t fpga_bitstream[] = {{
{body}
}};

static const size_t fpga_bitstream_len = sizeof(fpga_bitstream);
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=pathlib.Path, help="path to .bin bitstream")
    ap.add_argument("output", type=pathlib.Path, help="path to .h to write")
    args = ap.parse_args()

    data = args.input.read_bytes()
    if not data:
        sys.exit(f"error: {args.input} is empty")

    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(rows)

    args.output.write_text(HEADER.format(
        src=args.input.name,
        nbytes=len(data),
        body=body,
    ))
    print(f"wrote {args.output} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
