#include "board.h"
#include "fpga_prog.h"
#include "led.h"
#include "usb_serial.h"

// Generated by firmware/scripts/bin2c.py from fpga/build/bnn.bin.
// Provides:  extern const uint8_t fpga_bitstream[]; extern const size_t fpga_bitstream_len;
#include "bitstream.h"

#include "hardware/gpio.h"
#include "pico/stdlib.h"

#include <stdio.h>

#define FPGA_CLK_HZ (12 * 1000 * 1000)

static void blink_error(void) {
    while (true) {
        led_show_class(0);
        sleep_ms(120);
        led_off();
        sleep_ms(120);
    }
}

int main(void) {
    stdio_init_all();

    led_init();

    gpio_init(PIN_USER_BTN);
    gpio_set_dir(PIN_USER_BTN, GPIO_IN);
    gpio_pull_up(PIN_USER_BTN);

    // Give the host time to enumerate USB-CDC before we start printing.
    sleep_ms(2000);
    printf("\n[boot] BNN inference accelerator\n");

    fpga_prog_init();

    printf("[boot] starting FPGA clock @ %u Hz\n", FPGA_CLK_HZ);
    fpga_clock_start(FPGA_CLK_HZ);

    printf("[boot] loading bitstream (%u bytes)...\n", (unsigned)fpga_bitstream_len);
    if (!fpga_program(fpga_bitstream, fpga_bitstream_len)) {
        printf("[boot] FPGA configuration failed (CDONE never asserted)\n");
        blink_error();
    }
    printf("[boot] FPGA up. CDONE high.\n");

    while (true) {
        usb_serial_task();
        sleep_ms(5);
    }
}
